[env]
TERM = "screen-256color"

[font]
size = 14

# [font.bold]
# style = "Bold"

# to install the themes
# mkdir -p ~/.config/alacritty/themes
# git clone https://github.com/alacritty/alacritty-theme ~/.config/alacritty/themes

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# [[keyboard.bindings]]
# chars = "\u001BOH"
# key = "Left"
# mode = "AppCursor"
# mods = "Command"
#
# [[keyboard.bindings]]
# chars = "\u001BOF"
# key = "Right"
# mode = "AppCursor"
# mods = "Command"
#
[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"


[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Control"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Control"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Control"

[[keyboard.bindings]]
action = "None"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "None"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "A"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "B"
mode = "~Search"
mods = "Command"

[window]
opacity = 0.6
decorations = "none"
dynamic_padding = true

[window.padding]
x = 0
y = 0

[[keyboard.bindings]]
key = "Enter"
chars = "\r"

[[keyboard.bindings]]
key = "Back"
chars = "\u007f"

[general]
import = ["themes/bloodmoon.toml"]
